## IBM Capstone Project _ Canada

### Part 1: Scraping Table from Wikipedia Page

In [3]:
#import libraries
import numpy as np
import pandas as pd
import requests
!pip install lxml
!pip install html5lib
from bs4 import BeautifulSoup
print('finish')

Requirement already satisfied: lxml in /home/jupyterlab/conda/envs/python/lib/python3.6/site-packages (4.4.1)
Requirement already satisfied: html5lib in /home/jupyterlab/conda/envs/python/lib/python3.6/site-packages (0.9999999)
Requirement already satisfied: six in /home/jupyterlab/conda/envs/python/lib/python3.6/site-packages (from html5lib) (1.12.0)

ModuleNotFoundError: No module named 'bs4'

In [5]:
!pip install BeautifulSoup4
from bs4 import BeautifulSoup

Collecting BeautifulSoup4
  Downloading https://files.pythonhosted.org/packages/1a/b7/34eec2fe5a49718944e215fde81288eec1fa04638aa3fb57c1c6cd0f98c3/beautifulsoup4-4.8.0-py3-none-any.whl (97kB)
     |████████████████████████████████| 102kB 17.1MB/s ta 0:00:01
Collecting soupsieve>=1.2 (from BeautifulSoup4)
  Downloading https://files.pythonhosted.org/packages/0b/44/0474f2207fdd601bb25787671c81076333d2c80e6f97e92790f8887cf682/soupsieve-1.9.3-py2.py3-none-any.whl
Installing collected packages: soupsieve, BeautifulSoup4
Successfully installed BeautifulSoup4-4.8.0 soupsieve-1.9.3

In [6]:
page = 'https://en.wikipedia.org/wiki/List_of_postal_codes_of_Canada:_M'
wikitables = pd.read_html(page, attrs={'class':'wikitable'})
print(wikitables[0])

    Postcode           Borough          Neighbourhood
0        M1A      Not assigned           Not assigned
1        M2A      Not assigned           Not assigned
2        M3A        North York              Parkwoods
3        M4A        North York       Victoria Village
4        M5A  Downtown Toronto           Harbourfront
..       ...               ...                    ...
283      M8Z         Etobicoke              Mimico NW
284      M8Z         Etobicoke     The Queensway West
285      M8Z         Etobicoke  Royal York South West
286      M8Z         Etobicoke         South of Bloor
287      M9Z      Not assigned           Not assigned

[288 rows x 3 columns]

In [7]:
df = wikitables[0]
df

    Postcode           Borough          Neighbourhood
0        M1A      Not assigned           Not assigned
1        M2A      Not assigned           Not assigned
2        M3A        North York              Parkwoods
3        M4A        North York       Victoria Village
4        M5A  Downtown Toronto           Harbourfront
..       ...               ...                    ...
283      M8Z         Etobicoke              Mimico NW
284      M8Z         Etobicoke     The Queensway West
285      M8Z         Etobicoke  Royal York South West
286      M8Z         Etobicoke         South of Bloor
287      M9Z      Not assigned           Not assigned

[288 rows x 3 columns]

In [8]:
#Drop the 'Not assigned' rows
df = df[df.Borough != 'Not assigned']
df

    Postcode           Borough             Neighbourhood
2        M3A        North York                 Parkwoods
3        M4A        North York          Victoria Village
4        M5A  Downtown Toronto              Harbourfront
5        M5A  Downtown Toronto               Regent Park
6        M6A        North York          Lawrence Heights
..       ...               ...                       ...
282      M8Z         Etobicoke  Kingsway Park South West
283      M8Z         Etobicoke                 Mimico NW
284      M8Z         Etobicoke        The Queensway West
285      M8Z         Etobicoke     Royal York South West
286      M8Z         Etobicoke            South of Bloor

[211 rows x 3 columns]

In [9]:
#reset index
df.reset_index(drop=True, inplace=True)
df.head(20)

   Postcode           Borough     Neighbourhood
0       M3A        North York         Parkwoods
1       M4A        North York  Victoria Village
2       M5A  Downtown Toronto      Harbourfront
3       M5A  Downtown Toronto       Regent Park
4       M6A        North York  Lawrence Heights
5       M6A        North York    Lawrence Manor
6       M7A      Queen's Park      Not assigned
7       M9A         Etobicoke  Islington Avenue
8       M1B       Scarborough             Rouge
9       M1B       Scarborough           Malvern
10      M3B        North York   Don Mills North
11      M4B         East York  Woodbine Gardens
12      M4B         East York     Parkview Hill
13      M5B  Downtown Toronto           Ryerson
14      M5B  Downtown Toronto   Garden District
15      M6B        North York         Glencairn
16      M9B         Etobicoke        Cloverdale
17      M9B         Etobicoke         Islington
18      M9B         Etobicoke      Martin Grove
19      M9B         Etobicoke  Princess Gardens

In [10]:
#Find rows where Neighbourhood is stated as 'Not assigned'
df.loc[df['Neighbourhood'] == 'Not assigned']

  Postcode       Borough Neighbourhood
6      M7A  Queen's Park  Not assigned

In [11]:
df['Neighbourhood'].replace('Not assigned', "Queen's Park",inplace=True)
df.head(20)

/home/jupyterlab/conda/envs/python/lib/python3.6/site-packages/pandas/core/generic.py:6786: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  self._update_inplace(new_data)

   Postcode           Borough     Neighbourhood
0       M3A        North York         Parkwoods
1       M4A        North York  Victoria Village
2       M5A  Downtown Toronto      Harbourfront
3       M5A  Downtown Toronto       Regent Park
4       M6A        North York  Lawrence Heights
5       M6A        North York    Lawrence Manor
6       M7A      Queen's Park      Queen's Park
7       M9A         Etobicoke  Islington Avenue
8       M1B       Scarborough             Rouge
9       M1B       Scarborough           Malvern
10      M3B        North York   Don Mills North
11      M4B         East York  Woodbine Gardens
12      M4B         East York     Parkview Hill
13      M5B  Downtown Toronto           Ryerson
14      M5B  Downtown Toronto   Garden District
15      M6B        North York         Glencairn
16      M9B         Etobicoke        Cloverdale
17      M9B         Etobicoke         Islington
18      M9B         Etobicoke      Martin Grove
19      M9B         Etobicoke  Princess Gardens

In [12]:
#Merge duplicated rows
dup_Data=pd.DataFrame(df.duplicated(subset='Postcode'))
dup_Data

         0
0    False
1    False
2    False
3     True
4    False
..     ...
206  False
207   True
208   True
209   True
210   True

[211 rows x 1 columns]

In [13]:
#Create a new column to indicate duplication for the looping in next step
df['Duplicated?']=dup_Data.values
df

/home/jupyterlab/conda/envs/python/lib/python3.6/site-packages/ipykernel_launcher.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

    Postcode           Borough             Neighbourhood  Duplicated?
0        M3A        North York                 Parkwoods        False
1        M4A        North York          Victoria Village        False
2        M5A  Downtown Toronto              Harbourfront        False
3        M5A  Downtown Toronto               Regent Park         True
4        M6A        North York          Lawrence Heights        False
..       ...               ...                       ...          ...
206      M8Z         Etobicoke  Kingsway Park South West        False
207      M8Z         Etobicoke                 Mimico NW         True
208      M8Z         Etobicoke        The Queensway West         True
209      M8Z         Etobicoke     Royal York South West         True
210      M8Z         Etobicoke            South of Bloor         True

[211 rows x 4 columns]

In [14]:
#Create a new dataframe named newdf to store merged data
newdf = pd.DataFrame(columns = ['Duplicated?','Postcode', 'Borough', 'Neighbourhood'])
newdf

Empty DataFrame
Columns: [Duplicated?, Postcode, Borough, Neighbourhood]
Index: []

In [15]:
#Iterate through df to append non-duplicated rows to newdf, and add 'Neighbourhood' to the latest row of data in newdf for duplicated data in df
for i in range(0, len(df)-1):
    if df.loc[i, 'Duplicated?'] == False:
        newdf = newdf.append(df.iloc[i], ignore_index=True)
    else:
        newdf.loc[len(newdf)-1, 'Neighbourhood'] = newdf.loc[len(newdf)-1, 'Neighbourhood'] + ", " + df.loc[i, 'Neighbourhood']

In [16]:
newdf

,Duplicated?,Postcode,Borough,Neighbourhood
0,False,M3A,North York,Parkwoods
1,False,M4A,North York,Victoria Village
2,False,M5A,Downtown Toronto,"Harbourfront, Regent Park"
3,False,M6A,North York,"Lawrence Heights, Lawrence Manor"
4,False,M7A,Queen's Park,Queen's Park
...,...,...,...,...
98,False,M8X,Etobicoke,"The Kingsway, Montgomery Road, Old Mill North"
99,False,M4Y,Downtown Toronto,Church and Wellesley
100,False,M7Y,East Toronto,Business Reply Mail Processing Centre 969 Eastern
101,False,M8Y,Etobicoke,"Humber Bay, King's Mill Park, Kingsway Park So..."
102,False,M8Z,Etobicoke,"Kingsway Park South West, Mimico NW, The Queen..."

In [37]:
#Drop the duplicated column
newdf.drop(columns=['Duplicated?'], inplace=True)
newdf.head(10)

,Postcode,Borough,Neighbourhood,Latitude,Longitude
0,M3A,North York,Parkwoods,43.7533,-79.3297
1,M4A,North York,Victoria Village,43.7259,-79.3156
2,M5A,Downtown Toronto,"Harbourfront, Regent Park",43.6543,-79.3606
3,M6A,North York,"Lawrence Heights, Lawrence Manor",43.7185,-79.4648
4,M7A,Queen's Park,Queen's Park,43.6623,-79.3895
5,M9A,Etobicoke,Islington Avenue,43.6679,-79.5322
6,M1B,Scarborough,"Rouge, Malvern",43.8067,-79.1944
7,M3B,North York,Don Mills North,43.7459,-79.3522
8,M4B,East York,"Woodbine Gardens, Parkview Hill",43.7064,-79.3099
9,M5B,Downtown Toronto,"Ryerson, Garden District",43.6572,-79.3789

### Part 2： Create a dataframe with latitude and longitude columns

In [17]:
#Load csv file
coord_data = pd.read_csv("http://cocl.us/Geospatial_data")
coord_data

    Postal Code   Latitude  Longitude
0           M1B  43.806686 -79.194353
1           M1C  43.784535 -79.160497
2           M1E  43.763573 -79.188711
3           M1G  43.770992 -79.216917
4           M1H  43.773136 -79.239476
..          ...        ...        ...
98          M9N  43.706876 -79.518188
99          M9P  43.696319 -79.532242
100         M9R  43.688905 -79.554724
101         M9V  43.739416 -79.588437
102         M9W  43.706748 -79.594054

[103 rows x 3 columns]

In [19]:
coord_data['Postal Code']

0      M1B
1      M1C
2      M1E
3      M1G
4      M1H
      ...
98     M9N
99     M9P
100    M9R
101    M9V
102    M9W
Name: Postal Code, Length: 103, dtype: object

In [38]:
#Add empty columns to dataframe
newdf['Latitude'] = ""
newdf['Longitude'] = ""
newdf.head(20)

,Postcode,Borough,Neighbourhood,Latitude,Longitude
0,M3A,North York,Parkwoods,,
1,M4A,North York,Victoria Village,,
2,M5A,Downtown Toronto,"Harbourfront, Regent Park",,
3,M6A,North York,"Lawrence Heights, Lawrence Manor",,
4,M7A,Queen's Park,Queen's Park,,
5,M9A,Etobicoke,Islington Avenue,,
6,M1B,Scarborough,"Rouge, Malvern",,
7,M3B,North York,Don Mills North,,
8,M4B,East York,"Woodbine Gardens, Parkview Hill",,
9,M5B,Downtown Toronto,"Ryerson, Garden District",,
10,M6B,North York,Glencairn,,
11,M9B,Etobicoke,"Cloverdale, Islington, Martin Grove, Princess ...",,
12,M1C,Scarborough,"Highland Creek, Rouge Hill, Port Union",,
13,M3C,North York,"Flemingdon Park, Don Mills South",,
14,M4C,East York,Woodbine Heights,,
15,M5C,Downtown Toronto,St. James Town,,
16,M6C,York,Humewood-Cedarvale,,
17,M9C,Etobicoke,"Bloordale Gardens, Eringate, Markland Wood, Ol...",,
18,M1E,Scarborough,"Guildwood, Morningside, West Hill",,
19,M4E,East Toronto,The Beaches,,

In [39]:
#Copy newdf to testdf in case something goes wrong
testdf = newdf
testdf

,Postcode,Borough,Neighbourhood,Latitude,Longitude
0,M3A,North York,Parkwoods,,
1,M4A,North York,Victoria Village,,
2,M5A,Downtown Toronto,"Harbourfront, Regent Park",,
3,M6A,North York,"Lawrence Heights, Lawrence Manor",,
4,M7A,Queen's Park,Queen's Park,,
...,...,...,...,...,...
98,M8X,Etobicoke,"The Kingsway, Montgomery Road, Old Mill North",,
99,M4Y,Downtown Toronto,Church and Wellesley,,
100,M7Y,East Toronto,Business Reply Mail Processing Centre 969 Eastern,,
101,M8Y,Etobicoke,"Humber Bay, King's Mill Park, Kingsway Park So...",,
102,M8Z,Etobicoke,"Kingsway Park South West, Mimico NW, The Queen...",,

In [40]:
for a in range(0, len(testdf)):
    for b in range(0, len(coord_data)):
        if testdf.loc[a, 'Postcode'] == coord_data.loc[b, 'Postal Code']:
            testdf.loc[a, 'Latitude'] = coord_data.loc[b, 'Latitude']
            testdf.loc[a, 'Longitude'] = coord_data.loc[b, 'Longitude']

In [41]:
testdf

,Postcode,Borough,Neighbourhood,Latitude,Longitude
0,M3A,North York,Parkwoods,43.7533,-79.3297
1,M4A,North York,Victoria Village,43.7259,-79.3156
2,M5A,Downtown Toronto,"Harbourfront, Regent Park",43.6543,-79.3606
3,M6A,North York,"Lawrence Heights, Lawrence Manor",43.7185,-79.4648
4,M7A,Queen's Park,Queen's Park,43.6623,-79.3895
...,...,...,...,...,...
98,M8X,Etobicoke,"The Kingsway, Montgomery Road, Old Mill North",43.6537,-79.5069
99,M4Y,Downtown Toronto,Church and Wellesley,43.6659,-79.3832
100,M7Y,East Toronto,Business Reply Mail Processing Centre 969 Eastern,43.6627,-79.3216
101,M8Y,Etobicoke,"Humber Bay, King's Mill Park, Kingsway Park So...",43.6363,-79.4985
102,M8Z,Etobicoke,"Kingsway Park South West, Mimico NW, The Queen...",43.6288,-79.521

In [43]:
#Rename 'Postcode' to 'PostalCode'
testdf.rename(columns={'Postcode': 'PostalCode'}, inplace=True)
testdf

,PostalCode,Borough,Neighbourhood,Latitude,Longitude
0,M3A,North York,Parkwoods,43.7533,-79.3297
1,M4A,North York,Victoria Village,43.7259,-79.3156
2,M5A,Downtown Toronto,"Harbourfront, Regent Park",43.6543,-79.3606
3,M6A,North York,"Lawrence Heights, Lawrence Manor",43.7185,-79.4648
4,M7A,Queen's Park,Queen's Park,43.6623,-79.3895
...,...,...,...,...,...
98,M8X,Etobicoke,"The Kingsway, Montgomery Road, Old Mill North",43.6537,-79.5069
99,M4Y,Downtown Toronto,Church and Wellesley,43.6659,-79.3832
100,M7Y,East Toronto,Business Reply Mail Processing Centre 969 Eastern,43.6627,-79.3216
101,M8Y,Etobicoke,"Humber Bay, King's Mill Park, Kingsway Park So...",43.6363,-79.4985
102,M8Z,Etobicoke,"Kingsway Park South West, Mimico NW, The Queen...",43.6288,-79.521

### Part 3: Clustering Downtown Toronto

In [53]:
#import all libraries
import json # library to handle JSON files

!conda install -c conda-forge geopy --yes # uncomment this line if you haven't completed the Foursquare API lab
from geopy.geocoders import Nominatim # convert an address into latitude and longitude values

import requests # library to handle requests
from pandas.io.json import json_normalize # tranform JSON file into a pandas dataframe

# Matplotlib and associated plotting modules
import matplotlib.cm as cm
import matplotlib.colors as colors

# import k-means from clustering stage
from sklearn.cluster import KMeans

#!conda install -c conda-forge folium=0.5.0 --yes # uncomment this line if you haven't completed the Foursquare API lab
import folium # map rendering library

print('Libraries imported.')

Solving environment: done


==> WARNING: A newer version of conda exists. <==
  current version: 4.5.11
  latest version: 4.7.12

Please update conda by running

    $ conda update -n base -c defaults conda



## Package Plan ##

  environment location: /home/jupyterlab/conda/envs/python

  added / updated specs:
    - geopy


The following packages will be downloaded:

    package                    |            build
    ---------------------------|-----------------
    geopy-1.20.0               |             py_0          57 KB  conda-forge
    geographiclib-1.50         |             py_0          34 KB  conda-forge
    certifi-2019.9.11          |           py36_0         147 KB  conda-forge
    ------------------------------------------------------------
                                           Total:         238 KB

The following NEW packages will be INSTALLED:

    geographiclib: 1.50-py_0        conda-forge
    geopy:         1.20.0-py_0      conda-forge

The following packages will be UPDATED:

    certifi:       2019.6.16-py36_1 conda-forge --> 2019.9.11-py36_0 conda-forge


Downloading and Extracting Packages
geopy-1.20.0         | 57 KB     | ##################################### | 100%
geographiclib-1.50   | 34 KB     | ##################################### | 100%
certifi-2019.9.11    | 147 KB    | ##################################### | 100%
Preparing transaction: done
Verifying transaction: done
Executing transaction: done
Libraries imported.

In [52]:
#Set up df for downtown Toronto
dt_toronto = testdf[testdf['Borough'] == 'Downtown Toronto'].reset_index(drop=True)
dt_toronto.head()

  PostalCode           Borough              Neighbourhood Latitude Longitude
0        M5A  Downtown Toronto  Harbourfront, Regent Park  43.6543  -79.3606
1        M5B  Downtown Toronto   Ryerson, Garden District  43.6572  -79.3789
2        M5C  Downtown Toronto             St. James Town  43.6515  -79.3754
3        M5E  Downtown Toronto                Berczy Park  43.6448  -79.3733
4        M5G  Downtown Toronto         Central Bay Street   43.658  -79.3874

In [84]:
#Rename 'Neighbourhood' to 'Neighborhood'
dt_toronto.rename(columns={'Neighbourhood': 'Neighborhood'}, inplace=True)
dt_toronto

,PostalCode,Borough,Neighborhood,Latitude,Longitude
0,M5A,Downtown Toronto,"Harbourfront, Regent Park",43.6543,-79.3606
1,M5B,Downtown Toronto,"Ryerson, Garden District",43.6572,-79.3789
2,M5C,Downtown Toronto,St. James Town,43.6515,-79.3754
3,M5E,Downtown Toronto,Berczy Park,43.6448,-79.3733
4,M5G,Downtown Toronto,Central Bay Street,43.658,-79.3874
5,M6G,Downtown Toronto,Christie,43.6695,-79.4226
6,M5H,Downtown Toronto,"Adelaide, King, Richmond",43.6506,-79.3846
7,M5J,Downtown Toronto,"Harbourfront East, Toronto Islands, Union Station",43.6408,-79.3818
8,M5K,Downtown Toronto,"Design Exchange, Toronto Dominion Centre",43.6472,-79.3816
9,M5L,Downtown Toronto,"Commerce Court, Victoria Hotel",43.6482,-79.3798
10,M5S,Downtown Toronto,"Harbord, University of Toronto",43.6627,-79.4
11,M5T,Downtown Toronto,"Chinatown, Grange Park, Kensington Market",43.6532,-79.4
12,M5V,Downtown Toronto,"CN Tower, Bathurst Quay, Island airport, Harbo...",43.6289,-79.3944
13,M4W,Downtown Toronto,Rosedale,43.6796,-79.3775
14,M5W,Downtown Toronto,Stn A PO Boxes 25 The Esplanade,43.6464,-79.3748
15,M4X,Downtown Toronto,"Cabbagetown, St. James Town",43.668,-79.3677
16,M5X,Downtown Toronto,"First Canadian Place, Underground city",43.6484,-79.3823
17,M4Y,Downtown Toronto,Church and Wellesley,43.6659,-79.3832

In [54]:
#Set up Foursquare
CLIENT_ID = 'EY12SXK5E4AHWC0WWDRCKNQK3FARJI332FHKMDIQNXS5LYUB' # your Foursquare ID
CLIENT_SECRET = '0ELLT41YQUIEELH0QTYJUA0V2NEZ3OTZS45NVOTR1CE2VGUB' # your Foursquare Secret
VERSION = '20180605' # Foursquare API version

print('Your credentails:')
print('CLIENT_ID: ' + CLIENT_ID)
print('CLIENT_SECRET:' + CLIENT_SECRET)

Your credentails:
CLIENT_ID: EY12SXK5E4AHWC0WWDRCKNQK3FARJI332FHKMDIQNXS5LYUB
CLIENT_SECRET:0ELLT41YQUIEELH0QTYJUA0V2NEZ3OTZS45NVOTR1CE2VGUB

**Define function**

In [62]:
def getNearbyVenues(names, latitudes, longitudes, radius=500):
    
    venues_list=[]
    for name, lat, lng in zip(names, latitudes, longitudes):
        print(name)
            
        # create the API request URL
        url = 'https://api.foursquare.com/v2/venues/explore?&client_id={}&client_secret={}&v={}&ll={},{}&radius={}&limit={}'.format(
            CLIENT_ID, 
            CLIENT_SECRET, 
            VERSION, 
            lat, 
            lng, 
            radius, 
            LIMIT)
            
        # make the GET request
        results = requests.get(url).json()["response"]['groups'][0]['items']
        
        # return only relevant information for each nearby venue
        venues_list.append([(
            name, 
            lat, 
            lng, 
            v['venue']['name'], 
            v['venue']['location']['lat'], 
            v['venue']['location']['lng'],  
            v['venue']['categories'][0]['name']) for v in results])

    nearby_venues = pd.DataFrame([item for venue_list in venues_list for item in venue_list])
    nearby_venues.columns = ['Neighborhood', 
                  'Neighborhood Latitude', 
                  'Neighborhood Longitude', 
                  'Venue', 
                  'Venue Latitude', 
                  'Venue Longitude', 
                  'Venue Category']
    
    return(nearby_venues)

**Create df for downtown Toronto venues**

In [72]:
dt_toronto_venues = getNearbyVenues(names=dt_toronto['Neighbourhood'],
                                   latitudes=dt_toronto['Latitude'],
                                   longitudes=dt_toronto['Longitude']
                                  )

Harbourfront, Regent Park
Ryerson, Garden District
St. James Town
Berczy Park
Central Bay Street
Christie
Adelaide, King, Richmond
Harbourfront East, Toronto Islands, Union Station
Design Exchange, Toronto Dominion Centre
Commerce Court, Victoria Hotel
Harbord, University of Toronto
Chinatown, Grange Park, Kensington Market
CN Tower, Bathurst Quay, Island airport, Harbourfront West, King and Spadina, Railway Lands, South Niagara
Rosedale
Stn A PO Boxes 25 The Esplanade
Cabbagetown, St. James Town
First Canadian Place, Underground city
Church and Wellesley

In [73]:
print(dt_toronto_venues.shape)
dt_toronto_venues.head()

(1301, 7)

,Neighborhood,Neighborhood Latitude,Neighborhood Longitude,Venue,Venue Latitude,Venue Longitude,Venue Category
0,"Harbourfront, Regent Park",43.65426,-79.360636,Roselle Desserts,43.653447,-79.362017,Bakery
1,"Harbourfront, Regent Park",43.65426,-79.360636,Tandem Coffee,43.653559,-79.361809,Coffee Shop
2,"Harbourfront, Regent Park",43.65426,-79.360636,Toronto Cooper Koo Family Cherry St YMCA Centre,43.653191,-79.357947,Gym / Fitness Center
3,"Harbourfront, Regent Park",43.65426,-79.360636,Body Blitz Spa East,43.654735,-79.359874,Spa
4,"Harbourfront, Regent Park",43.65426,-79.360636,Impact Kitchen,43.656369,-79.356980,Restaurant

In [65]:
dt_toronto_venues.groupby('Neighborhood').count()

,Neighborhood Latitude,Neighborhood Longitude,Venue,Venue Latitude,Venue Longitude,Venue Category
Neighborhood,,,,,,
"Adelaide, King, Richmond",100,100,100,100,100,100
Berczy Park,57,57,57,57,57,57
"CN Tower, Bathurst Quay, Island airport, Harbourfront West, King and Spadina, Railway Lands, South Niagara",15,15,15,15,15,15
"Cabbagetown, St. James Town",46,46,46,46,46,46
Central Bay Street,86,86,86,86,86,86
"Chinatown, Grange Park, Kensington Market",100,100,100,100,100,100
Christie,16,16,16,16,16,16
Church and Wellesley,92,92,92,92,92,92
"Commerce Court, Victoria Hotel",100,100,100,100,100,100
"Design Exchange, Toronto Dominion Centre",100,100,100,100,100,100
"First Canadian Place, Underground city",100,100,100,100,100,100
"Harbord, University of Toronto",35,35,35,35,35,35
"Harbourfront East, Toronto Islands, Union Station",100,100,100,100,100,100
"Harbourfront, Regent Park",51,51,51,51,51,51
Rosedale,5,5,5,5,5,5
"Ryerson, Garden District",100,100,100,100,100,100
St. James Town,100,100,100,100,100,100
Stn A PO Boxes 25 The Esplanade,98,98,98,98,98,98

In [74]:
# one hot encoding
dt_toronto_onehot = pd.get_dummies(dt_toronto_venues[['Venue Category']], prefix="", prefix_sep="")

# add neighborhood column back to dataframe
dt_toronto_onehot['Neighborhood'] = dt_toronto_venues['Neighborhood'] 

# move neighborhood column to the first column
fixed_columns = [dt_toronto_onehot.columns[-1]] + list(dt_toronto_onehot.columns[:-1])
dt_toronto_onehot = dt_toronto_onehot[fixed_columns]

dt_toronto_onehot.head()

,Yoga Studio,Afghan Restaurant,Airport,Airport Food Court,Airport Lounge,Airport Service,Airport Terminal,American Restaurant,Antique Shop,Aquarium,...,Theater,Theme Restaurant,Toy / Game Store,Trail,Train Station,Vegetarian / Vegan Restaurant,Video Game Store,Vietnamese Restaurant,Wine Bar,Wings Joint
0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [70]:
dt_toronto_onehot.shape

(1301, 209)

**Next, group rows by neighborhood and by taking the mean of the frequency of occurrence of each category**

In [76]:
dt_toronto_grouped = dt_toronto_onehot.groupby('Neighborhood').mean().reset_index()
dt_toronto_grouped

,Neighborhood,Yoga Studio,Afghan Restaurant,Airport,Airport Food Court,Airport Lounge,Airport Service,Airport Terminal,American Restaurant,Antique Shop,...,Theater,Theme Restaurant,Toy / Game Store,Trail,Train Station,Vegetarian / Vegan Restaurant,Video Game Store,Vietnamese Restaurant,Wine Bar,Wings Joint
0,"Adelaide, King, Richmond",0.000000,0.00000,0.000000,0.000000,0.000000,0.000000,0.000000,0.030000,0.000000,...,0.010000,0.00000,0.00,0.0,0.00,0.020000,0.000000,0.00000,0.010000,0.00000
1,Berczy Park,0.000000,0.00000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.00000,0.00,0.0,0.00,0.017544,0.000000,0.00000,0.000000,0.00000
2,"CN Tower, Bathurst Quay, Island airport, Harbo...",0.000000,0.00000,0.066667,0.066667,0.133333,0.133333,0.133333,0.000000,0.000000,...,0.000000,0.00000,0.00,0.0,0.00,0.000000,0.000000,0.00000,0.000000,0.00000
3,"Cabbagetown, St. James Town",0.000000,0.00000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.00000,0.00,0.0,0.00,0.000000,0.000000,0.00000,0.000000,0.00000
4,Central Bay Street,0.011628,0.00000,0.000000,0.000000,0.000000,0.000000,0.000000,0.011628,0.000000,...,0.000000,0.00000,0.00,0.0,0.00,0.011628,0.000000,0.00000,0.011628,0.00000
5,"Chinatown, Grange Park, Kensington Market",0.000000,0.00000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.00000,0.01,0.0,0.00,0.060000,0.000000,0.04000,0.010000,0.00000
6,Christie,0.000000,0.00000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.00000,0.00,0.0,0.00,0.000000,0.000000,0.00000,0.000000,0.00000
7,Church and Wellesley,0.010870,0.01087,0.000000,0.000000,0.000000,0.000000,0.000000,0.010870,0.000000,...,0.010870,0.01087,0.00,0.0,0.00,0.000000,0.010870,0.01087,0.000000,0.01087
8,"Commerce Court, Victoria Hotel",0.000000,0.00000,0.000000,0.000000,0.000000,0.000000,0.000000,0.040000,0.000000,...,0.000000,0.00000,0.00,0.0,0.00,0.020000,0.000000,0.00000,0.010000,0.00000
9,"Design Exchange, Toronto Dominion Centre",0.000000,0.00000,0.000000,0.000000,0.000000,0.000000,0.000000,0.030000,0.000000,...,0.010000,0.00000,0.00,0.0,0.01,0.010000,0.000000,0.00000,0.010000,0.00000
10,"First Canadian Place, Underground city",0.000000,0.00000,0.000000,0.000000,0.000000,0.000000,0.000000,0.030000,0.000000,...,0.010000,0.00000,0.00,0.0,0.01,0.010000,0.000000,0.00000,0.010000,0.00000
11,"Harbord, University of Toronto",0.028571,0.00000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.057143,0.00000,0.00,0.0,0.00,0.000000,0.028571,0.00000,0.000000,0.00000
12,"Harbourfront East, Toronto Islands, Union Station",0.000000,0.00000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.010000,0.00000,0.00,0.0,0.01,0.010000,0.000000,0.00000,0.010000,0.00000
13,"Harbourfront, Regent Park",0.019608,0.00000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.019608,...,0.039216,0.00000,0.00,0.0,0.00,0.000000,0.000000,0.00000,0.000000,0.00000
14,Rosedale,0.000000,0.00000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.00000,0.00,0.2,0.00,0.000000,0.000000,0.00000,0.000000,0.00000
15,"Ryerson, Garden District",0.000000,0.00000,0.000000,0.000000,0.000000,0.000000,0.000000,0.010000,0.000000,...,0.020000,0.00000,0.01,0.0,0.00,0.010000,0.010000,0.01000,0.010000,0.00000
16,St. James Town,0.000000,0.00000,0.000000,0.000000,0.000000,0.000000,0.000000,0.020000,0.000000,...,0.010000,0.00000,0.00,0.0,0.00,0.010000,0.000000,0.00000,0.010000,0.00000
17,Stn A PO Boxes 25 The Esplanade,0.000000,0.00000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.010204,...,0.000000,0.00000,0.00,0.0,0.00,0.010204,0.000000,0.00000,0.000000,0.00000

In [77]:
dt_toronto_grouped.shape

(18, 209)

**Create a new dataframe with the most popular venues as columns**

In [80]:
def return_most_common_venues(row, num_top_venues):
    row_categories = row.iloc[1:]
    row_categories_sorted = row_categories.sort_values(ascending=False)
    
    return row_categories_sorted.index.values[0:num_top_venues]

In [82]:
num_top_venues = 10

indicators = ['st', 'nd', 'rd']

# create columns according to number of top venues
columns = ['Neighborhood']
for ind in np.arange(num_top_venues):
    try:
        columns.append('{}{} Most Common Venue'.format(ind+1, indicators[ind]))
    except:
        columns.append('{}th Most Common Venue'.format(ind+1))

# create a new dataframe
neighborhoods_venues_sorted = pd.DataFrame(columns=columns)
neighborhoods_venues_sorted['Neighborhood'] = dt_toronto_grouped['Neighborhood']

for ind in np.arange(dt_toronto_grouped.shape[0]):
    neighborhoods_venues_sorted.iloc[ind, 1:] = return_most_common_venues(dt_toronto_grouped.iloc[ind, :], num_top_venues)

neighborhoods_venues_sorted.head()

,Neighborhood,1st Most Common Venue,2nd Most Common Venue,3rd Most Common Venue,4th Most Common Venue,5th Most Common Venue,6th Most Common Venue,7th Most Common Venue,8th Most Common Venue,9th Most Common Venue,10th Most Common Venue
0,"Adelaide, King, Richmond",Coffee Shop,Café,Steakhouse,Bar,Cosmetics Shop,American Restaurant,Thai Restaurant,Restaurant,Hotel,Burger Joint
1,Berczy Park,Coffee Shop,Cocktail Bar,Steakhouse,Cheese Shop,Italian Restaurant,Beer Bar,Seafood Restaurant,Farmers Market,Bakery,Café
2,"CN Tower, Bathurst Quay, Island airport, Harbo...",Airport Lounge,Airport Service,Airport Terminal,Coffee Shop,Harbor / Marina,Boat or Ferry,Bar,Sculpture Garden,Plane,Boutique
3,"Cabbagetown, St. James Town",Coffee Shop,Italian Restaurant,Bakery,Park,Pharmacy,Pizza Place,Restaurant,Pub,Café,Diner
4,Central Bay Street,Coffee Shop,Café,Italian Restaurant,Middle Eastern Restaurant,Sandwich Place,Burger Joint,Ice Cream Shop,Bar,Sushi Restaurant,Chinese Restaurant

**Start to do clustering!**

Run *k*-means to cluster the neighborhood into 5 clusters.

In [78]:
# set number of clusters
kclusters = 5

dt_toronto_grouped_clustering = dt_toronto_grouped.drop('Neighborhood', 1)

# run k-means clustering
kmeans = KMeans(n_clusters=kclusters, random_state=0).fit(dt_toronto_grouped_clustering)

# check cluster labels generated for each row in the dataframe
kmeans.labels_[0:10]

array([0, 0, 3, 0, 0, 2, 4, 0, 0, 0], dtype=int32)

Let's create a new dataframe that includes the cluster as well as the top 10 venues for each neighborhood.

In [92]:
# add clustering labels
#neighborhoods_venues_sorted.insert(0, 'Cluster Labels', kmeans.labels_)

dt_toronto_merged = dt_toronto

# merge toronto_grouped with toronto_data to add latitude/longitude for each neighborhood
dt_toronto_merged = dt_toronto_merged.join(neighborhoods_venues_sorted.set_index('Neighborhood'), on='Neighborhood')

dt_toronto_merged.drop(columns=['PostalCode'], inplace=True)

dt_toronto_merged.head() # check the last columns!

,Borough,Neighborhood,Latitude,Longitude,Cluster Labels,1st Most Common Venue,2nd Most Common Venue,3rd Most Common Venue,4th Most Common Venue,5th Most Common Venue,6th Most Common Venue,7th Most Common Venue,8th Most Common Venue,9th Most Common Venue,10th Most Common Venue
0,Downtown Toronto,"Harbourfront, Regent Park",43.6543,-79.3606,0,Coffee Shop,Bakery,Pub,Café,Park,Mexican Restaurant,Gym / Fitness Center,Breakfast Spot,Restaurant,Theater
1,Downtown Toronto,"Ryerson, Garden District",43.6572,-79.3789,0,Coffee Shop,Clothing Store,Middle Eastern Restaurant,Cosmetics Shop,Café,Japanese Restaurant,Restaurant,Diner,Bakery,Plaza
2,Downtown Toronto,St. James Town,43.6515,-79.3754,0,Coffee Shop,Café,Hotel,Restaurant,Italian Restaurant,Breakfast Spot,Clothing Store,Cocktail Bar,Beer Bar,Cosmetics Shop
3,Downtown Toronto,Berczy Park,43.6448,-79.3733,0,Coffee Shop,Cocktail Bar,Steakhouse,Cheese Shop,Italian Restaurant,Beer Bar,Seafood Restaurant,Farmers Market,Bakery,Café
4,Downtown Toronto,Central Bay Street,43.658,-79.3874,0,Coffee Shop,Café,Italian Restaurant,Middle Eastern Restaurant,Sandwich Place,Burger Joint,Ice Cream Shop,Bar,Sushi Restaurant,Chinese Restaurant

**Visualisation**

In [89]:
#Set log & lat of Toronto
latitude = 43.6532
longitude = -79.3832

# create map
map_clusters = folium.Map(location=[latitude, longitude], zoom_start=11)

# set color scheme for the clusters
x = np.arange(kclusters)
ys = [i + x + (i*x)**2 for i in range(kclusters)]
colors_array = cm.rainbow(np.linspace(0, 1, len(ys)))
rainbow = [colors.rgb2hex(i) for i in colors_array]

# add markers to the map
markers_colors = []
for lat, lon, poi, cluster in zip(dt_toronto_merged['Latitude'], dt_toronto_merged['Longitude'], dt_toronto_merged['Neighborhood'], dt_toronto_merged['Cluster Labels']):
    label = folium.Popup(str(poi) + ' Cluster ' + str(cluster), parse_html=True)
    folium.CircleMarker(
        [lat, lon],
        radius=5,
        popup=label,
        color=rainbow[cluster-1],
        fill=True,
        fill_color=rainbow[cluster-1],
        fill_opacity=0.7).add_to(map_clusters)
       
map_clusters

**Cluster Examination**

**_Cluster 1_**

In [93]:
dt_toronto_merged.loc[dt_toronto_merged['Cluster Labels'] == 0, dt_toronto_merged.columns[[1] + list(range(5, dt_toronto_merged.shape[1]))]]

,Neighborhood,1st Most Common Venue,2nd Most Common Venue,3rd Most Common Venue,4th Most Common Venue,5th Most Common Venue,6th Most Common Venue,7th Most Common Venue,8th Most Common Venue,9th Most Common Venue,10th Most Common Venue
0,"Harbourfront, Regent Park",Coffee Shop,Bakery,Pub,Café,Park,Mexican Restaurant,Gym / Fitness Center,Breakfast Spot,Restaurant,Theater
1,"Ryerson, Garden District",Coffee Shop,Clothing Store,Middle Eastern Restaurant,Cosmetics Shop,Café,Japanese Restaurant,Restaurant,Diner,Bakery,Plaza
2,St. James Town,Coffee Shop,Café,Hotel,Restaurant,Italian Restaurant,Breakfast Spot,Clothing Store,Cocktail Bar,Beer Bar,Cosmetics Shop
3,Berczy Park,Coffee Shop,Cocktail Bar,Steakhouse,Cheese Shop,Italian Restaurant,Beer Bar,Seafood Restaurant,Farmers Market,Bakery,Café
4,Central Bay Street,Coffee Shop,Café,Italian Restaurant,Middle Eastern Restaurant,Sandwich Place,Burger Joint,Ice Cream Shop,Bar,Sushi Restaurant,Chinese Restaurant
6,"Adelaide, King, Richmond",Coffee Shop,Café,Steakhouse,Bar,Cosmetics Shop,American Restaurant,Thai Restaurant,Restaurant,Hotel,Burger Joint
7,"Harbourfront East, Toronto Islands, Union Station",Coffee Shop,Aquarium,Hotel,Café,Brewery,Fried Chicken Joint,Scenic Lookout,Plaza,Sporting Goods Shop,Sports Bar
8,"Design Exchange, Toronto Dominion Centre",Coffee Shop,Café,Hotel,Restaurant,Bakery,Bar,Italian Restaurant,Deli / Bodega,Gastropub,American Restaurant
9,"Commerce Court, Victoria Hotel",Coffee Shop,Hotel,Café,Restaurant,American Restaurant,Deli / Bodega,Italian Restaurant,Seafood Restaurant,Gym,Steakhouse
14,Stn A PO Boxes 25 The Esplanade,Coffee Shop,Restaurant,Italian Restaurant,Café,Beer Bar,Hotel,Seafood Restaurant,Cocktail Bar,Park,Gym
15,"Cabbagetown, St. James Town",Coffee Shop,Italian Restaurant,Bakery,Park,Pharmacy,Pizza Place,Restaurant,Pub,Café,Diner
16,"First Canadian Place, Underground city",Coffee Shop,Café,Hotel,Restaurant,Steakhouse,American Restaurant,Bar,Gym,Deli / Bodega,Asian Restaurant
17,Church and Wellesley,Coffee Shop,Gay Bar,Japanese Restaurant,Sushi Restaurant,Restaurant,Men's Store,Gastropub,Gym,Hotel,Mediterranean Restaurant

**_Cluster 2_**

In [94]:
dt_toronto_merged.loc[dt_toronto_merged['Cluster Labels'] == 1, dt_toronto_merged.columns[[1] + list(range(5, dt_toronto_merged.shape[1]))]]

,Neighborhood,1st Most Common Venue,2nd Most Common Venue,3rd Most Common Venue,4th Most Common Venue,5th Most Common Venue,6th Most Common Venue,7th Most Common Venue,8th Most Common Venue,9th Most Common Venue,10th Most Common Venue
13,Rosedale,Park,Playground,Trail,Building,Wings Joint,Department Store,Eastern European Restaurant,Dumpling Restaurant,Donut Shop,Doner Restaurant

**_Cluster 3_**

In [96]:
dt_toronto_merged.loc[dt_toronto_merged['Cluster Labels'] == 2, dt_toronto_merged.columns[[1] + list(range(5, dt_toronto_merged.shape[1]))]]

,Neighborhood,1st Most Common Venue,2nd Most Common Venue,3rd Most Common Venue,4th Most Common Venue,5th Most Common Venue,6th Most Common Venue,7th Most Common Venue,8th Most Common Venue,9th Most Common Venue,10th Most Common Venue
10,"Harbord, University of Toronto",Café,Theater,Japanese Restaurant,Bookstore,Sandwich Place,Restaurant,Bakery,Bar,Pub,Dessert Shop
11,"Chinatown, Grange Park, Kensington Market",Café,Vegetarian / Vegan Restaurant,Bar,Bakery,Vietnamese Restaurant,Chinese Restaurant,Dumpling Restaurant,Mexican Restaurant,Coffee Shop,Gaming Cafe

**_Cluster 4_**

In [97]:
dt_toronto_merged.loc[dt_toronto_merged['Cluster Labels'] == 3, dt_toronto_merged.columns[[1] + list(range(5, dt_toronto_merged.shape[1]))]]

,Neighborhood,1st Most Common Venue,2nd Most Common Venue,3rd Most Common Venue,4th Most Common Venue,5th Most Common Venue,6th Most Common Venue,7th Most Common Venue,8th Most Common Venue,9th Most Common Venue,10th Most Common Venue
12,"CN Tower, Bathurst Quay, Island airport, Harbo...",Airport Lounge,Airport Service,Airport Terminal,Coffee Shop,Harbor / Marina,Boat or Ferry,Bar,Sculpture Garden,Plane,Boutique

**_Cluster 5_**

In [98]:
dt_toronto_merged.loc[dt_toronto_merged['Cluster Labels'] == 4, dt_toronto_merged.columns[[1] + list(range(5, dt_toronto_merged.shape[1]))]]

,Neighborhood,1st Most Common Venue,2nd Most Common Venue,3rd Most Common Venue,4th Most Common Venue,5th Most Common Venue,6th Most Common Venue,7th Most Common Venue,8th Most Common Venue,9th Most Common Venue,10th Most Common Venue
5,Christie,Grocery Store,Café,Park,Athletics & Sports,Restaurant,Italian Restaurant,Diner,Nightclub,Baby Store,Convenience Store

# Thank you for reviewing! :)